const REMODELATION_JSON_ARRAY_copy = [
  {
    id: 15,
    chartId: 4,
    name: "1era Etapa de Infraestructura",    
    cords: {
      x: 332,
      y: 298
    }
  },
  {
    id: 3,
    chartId: "23",
    name: "Área de Cuerdas",
    area: 770,
    description: "Los Talleres de Cuerdas son actividades de campo abierto que involucran desafíos físicos y mentales orientados a resolver problemas, fomentando aprendizajes, autoanálisis y competencias para el trabajo en equipo.", 
    antiproject: "Si",
    design: "No",
    designer: "Sanjoseres (Anteproyecto)",
    source: "Obras adicionales (año 2017)",
    costM: 1412,
    estimatedCost: 1086957,
    lastDate: "mar-23",
    cords: {
      x: 756,
      y: 434,
    },
    renders: null,
  }

  ,
  {
    id: 5,
    chartId: "5",
    name: "Centro de Tecnologia y Artes Visuales (CETAV)",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:403 ,
      y:279 ,
    },
    renders: "NO",
  },
  {
    id: 6,
    chartId: "6",
    name: "SINEM Parque La Libertad",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:501 ,
      y:287 ,
    },
    renders: "NO",
  },
  {
    id: 7,
    chartId: "7",
    name: "Anexo SINEM Parque La Libertad",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:526 ,
      y:269 ,
    },
    renders: "NO",
  },
  {
    id: 11,
    chartId: "11",
    name: "Laguna de Retención",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:635 ,
      y:415 ,
    },
    renders: "NO",
  },
  {
    id: 12,
    chartId: "12",
    name: "Cancha de Fútbol",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:624 ,
      y:527 ,
    },
    renders: "NO",
  },
  {
    id: 13,
    chartId: "13",
    name: "Cancha de Basket",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:672 ,
      y:569 ,
    },
    renders: "NO",
  },
  {
    id: 14,
    chartId: "14",
    name: "Escuela de Danza, Teatro y Circo",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:634 ,
      y:230 ,
    },
    renders: "NO",
  },
  {
    id: 15,
    chartId: "15",
    name: "Centro Infantil y Juvenil (CI)",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:675 ,
      y:250 ,
    },
    renders: "NO",
  },
  {
    id: 16,
    chartId: "16",
    name: "Centro de Atención PANI",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:698 ,
      y:260 ,
    },
    renders: "NO",
  },
  {
    id: 18,
    chartId: "18",
    name: "Planta de Tratamiento",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x:257,
      y:114,
    },
    renders: "NO",
  },
  {
    id: 24,
    chartId: "24",
    name: "Parque de Parkour",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 723,
      y: 449,
    },
    renders: "NO",
  },
  {
    id: 25,
    chartId: "25",
    name: "DOMO",
    description: "...",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 539 ,
      y: 350 ,
    },
    renders: "NO",
  },
];

export default REMODELATION_JSON_ARRAY_copy;
