const NOT_BUILT_JSON_ARRAY = [{
    id: "C",
    chartId: "C",
    name: "Infraestructura Etapa 2°",
    description: "Conjunto de medios técnicos, servicios e instalaciones que componen la vía pública del Parque, necesarios para tránsito de personas y vehículos en forma segura y confortable de un punto a otro. Incluye: red vial, ciclo vía, sistemas de alcantarillado pluvial, sistema sanitario, sistemas de telecomunicaciones, red eléctrica. Estas obras serán complemento de la infraestructura existente de la 1° Etapa. ",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 224,
    estimatedCost: 2717391,
    lastDate: "mar-23",
    cords: {
      x: 603,
      y: 378,
    },
    renders: null,
  },
  {
    id: "H",
    chartId: "H",
    name: "Anfiteatro",
    area: 4300,
    description: "Se trata de una estructura que puede tener forma circular, ovalada o similar y que dispone de gradas, desde donde el público puede observar diferentes tipos de eventos. Además, sirven de lugar de encuentro tanto para estudiantes como profesores para dar conferencias y eventos de gran importancia",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 500,
    estimatedCost: 2150000,
    lastDate: "mar-23",
    cords: {
      x: 716,
      y: 387,
    },
    renders: null,
  },
   {
    id: "A",
    chartId: "A",
    name: "Centro de Acopio",
    description: "Lugar destinado a la concentración de los residuos aprovechables inorgánicos, como papel, cartón, vidrio, plástico, metal, entre otros, para ser separados y luego comercializados para beneficio de la población recicladoras de la ciudad.",
    antiproject: false,
    design: false,
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 301,
      y: 381,
    },
    renders: "Si",
  },
   {
    id: "B",
    chartId: "B",
    name: "Acceso al Centro de Acopio",
    cords: {
      x: 319,
      y: 377,
    },
  },
  {
    id: "O",
    chartId: "O",
    name: "Infraestructura 4° Etapa ",
    description:  "Conjunto de medios técnicos, servicios e instalaciones que componen la vía pública del Parque, necesarios para tránsito de personas y vehículos en forma segura y confortable de un punto a otro. Incluye: red vial, ciclo vía, sistemas de alcantarillado pluvial, sistema sanitario, sistemas de telecomunicaciones, red eléctrica. Estas obras serán complemento de la infraestructura de la 2° y 3° Etapa. ",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 443,
      y: 210,
    },
    renders: null,
  },
  {
    id: "I",
    chartId: "I",
    name: "Edificio Circo",
    area: null,
    description: "Espacio destinado al espectáculo artístico, en donde se fomentarán las clases circenses, acróbatas, malabaristas, entre otros.",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: 1200,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 611,
      y: 212,
    },
    renders: null,
  },
  {
    id: "K",
    chartId: "K",
    name: "Gradería y camerinos deportivos",
    description: "Esta obra será un complemento para la zona deportiva del Parque, en donde las personas tendrán acceso a camerinos, servicios sanitarios y duchas. Además la gradería paralela a la cancha de fútbol para que los visitantes puedan observar las diferentes actividades deportivas que se desarrollen en esa zona. ",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: 500000,
    lastDate: "mar-23",
    cords: {
      x: 582.2,
      y: 552,
    },
    renders: null,
  },
  {
    id: "N",
    area: 12148,
    chartId: "N",
    name: "Infraestructura Etapa 3°",
    description: "Conjunto de medios técnicos, servicios e instalaciones que componen la vía pública del Parque, necesarios para tránsito de personas y vehículos en forma segura y confortable de un punto a otro. Incluye: red vial, ciclo vía, sistemas de alcantarillado pluvial, sistema sanitario, sistemas de telecomunicaciones, red eléctrica. Estas obras serán complemento de la infraestructura existente de la 1° Etapa. ",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 224,
    estimatedCost: 2717391,
    cords: {
      x: 321,
      y: 181,
    },
    renders: null,
  },
  {
    id: "M",
    area: 4356,
    chartId: "M",
    name: " protección naciente y acceso este al parque",
    description: "Esta obra brindará un mejor acceso y acercamiento con la comunidad de Linda Vista. Estos trabajos incluyen: caseta de seguridad,senderos y estaciones de descanso.",
    antiproject: "SÍ",
    design: "SÍ",
    designer: "Gabriel Calvo Viquez A-21654",
    source: "Obras adicionales",
    costM: 80,
    estimatedCost: 350000,
    lastDate: "mar-23",
    cords: {
      x: 1006,
      y: 400,
    },
    renders: "SÍ (planos en físico)",
  },
  {
    id: "D",
    chartId: "D",
    name: "Pórtico Entrada Fátima",
    description: "Mejoramiento en entrada de Fátima. Construcción de nueva caseta y mejoramiento de accesos.",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Obras adicionales",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 333,
      y: 334,
    },
    renders: null,
  },
  {
    id: "E",
    chartId: "E",
    name: "Módulo de servicios básicos",
    area: 770,
    description: "Se trata de un espacio en donde los isitantes del Parque tendrán acceso a servicios sanitarios, área de comidas y espacios comunes. ",
    antiproject: "Si",
    design: "No",
    designer: "Sanjoseres (Anteproyecto)",
    source: "Obras adicionales (año 2017)",
    costM: 1412,
    estimatedCost: 1086957,
    lastDate: "mar-23",
    cords: {
      x: 513,
      y: 365,
    },
    renders: null,
  },
  {
    id: "J",
    chartId: "J",
    name: "Edificio 'Espacio CoCreativo'",
     cords: {
      x:650 ,
      y:255 ,
    },
    renders: null,
  },
  {
    id: "L",
    chartId: "L",
    name: "Centro de Innocacion y Economia Creativa",
     cords: {
      x:563 ,
      y:243 ,
    },
    renders: null,
  },
  {
    id: "F",
    chartId: "F",
    name: "Oficinas de Juventudes- Aulas",
     cords: {
      x:558 ,
      y:427 ,
    },
    renders: null,
  },
  {
    id: "G",
    chartId: "G",
    name: "Plazoleta Multiusos",
     cords: {
      x:537 ,
      y:439 ,
    },
    renders: null,
  },
];

export default NOT_BUILT_JSON_ARRAY;