const NOT_BUILT_JSON_ARRAY = [{
    id: 1,
    chartId: "C",
    name: "Infraestructura Etapa 2°",
    description: "...",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 224,
    estimatedCost: 2717391,
    lastDate: "mar-23",
    cords: {
      x: 603,
      y: 378,
    },
    renders: null,
  },
  {
    id: 2,
    chartId: "H",
    name: "Anfiteatro",
    area: 4300,
    description: "...",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 500,
    estimatedCost: 2150000,
    lastDate: "mar-23",
    cords: {
      x: 716,
      y: 387,
    },
    renders: null,
  },
   {
    id: 5,
    chartId: "A",
    name: "Centro de Acopio",
    description: "...",
    antiproject: false,
    design: false,
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 301,
      y: 381,
    },
    renders: "Si",
  },
  {
    id: 6,
    chartId: "O",
    name: "Infraestructura 4° Etapa ",
    description: "...",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 443,
      y: 210,
    },
    renders: "No",
  },
  {
    id: 7,
    chartId: "I",
    name: "Edificio Circo",
    area: null,
    description: "Espacio destinado al espectáculo artístico, en donde se fomentarán las clases circenses, acróbatas, malabaristas, entre otros.",
    antiproject: "NO",
    design: "NO",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: 1200,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 611,
      y: 212,
    },
    renders: "NO",
  },
  {
    id: 9,
    chartId: "K",
    name: "Gradería y camerinos deportivos",
    description: "...",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Plan Maestro Inicial (año 2012)",
    costM: null,
    estimatedCost: 500000,
    lastDate: "mar-23",
    cords: {
      x: 582.2,
      y: 552,
    },
    renders: "No",
  },
  {
    id: 10,
    area: 12148,
    chartId: "N",
    name: "Infraestructura Etapa 3°",
    description: "...",
    antiproject: "Si",
    design: "Si (Planos fisicos)",
    designer: "Sanjoseres (Planos)",
    source: "Plan Maestro Inicial (año 2012)",
    costM: 224,
    estimatedCost: 2717391,
    cords: {
      x: 321,
      y: 181,
    },
    renders: null,
  },
  {
    id: 11,
    chartId: "?",
    name: "Acceso Linda Vista",
    description: "...",
    antiproject: "SÍ",
    design: "SÍ",
    designer: "Gabriel Calvo Viquez A-21654",
    source: "Obras adicionales",
    costM: null,
    estimatedCost: 350000,
    lastDate: "mar-23",
    cords: {
      x: 687,
      y: 217
    },
    renders: "SÍ (planos en físico)",
  },
  {
    id: 13,
    chartId: "D",
    name: "Pórtico Entrada Fátima",
    description: "...",
    antiproject: "No",
    design: "No",
    designer: null,
    source: "Obras adicionales",
    costM: null,
    estimatedCost: null,
    lastDate: "mar-23",
    cords: {
      x: 333,
      y: 334,
    },
    renders: "No",
  },
  {
    id: 23,
    chartId: "E",
    name: "Módulo de servicios básicos",
    area: 770,
    description: "...",
    antiproject: "Si",
    design: "No",
    designer: "Sanjoseres (Anteproyecto)",
    source: "Obras adicionales (año 2017)",
    costM: 1412,
    estimatedCost: 1086957,
    lastDate: "mar-23",
    cords: {
      x: 513,
      y: 365,
    },
    renders: null,
  },
];

export default NOT_BUILT_JSON_ARRAY;